import { initSeo } from "remix-seo";
export const { getSeo, getSeoMeta, getSeoLinks } = initSeo({
	// Pass any SEO defaults for your site here.
	// If individual routes do not provide their own meta and link tags,
	// the tags generated by the defaults will be used.
	title: "Element Softworks",
	titleTemplate: "%s • Element Softworks",
	description: "Innovative, modern, creative, we are Element Softworks.",
});
